"""Which worlds an agent trains on, and which it is judged on.

Training on one map teaches one map. This is the best established result in the field:
Procgen and CoinRun both show that an agent given a fixed set of levels memorises them,
and that generalisation only appears once the training set runs into the hundreds. No
amount of reward tuning substitutes for it.

Mindustry hands us the fix for free. Serpulo is a planet of several hundred sectors, and
every one without a hand-made preset is generated by the game's own planet generator: its
own terrain, its own ore, its own size. An agent that meets a new world every episode
cannot learn where the copper is. It has to learn what copper looks like.

The split is the other half. A training set says nothing about generalisation on its own,
because a number that goes up on the maps you trained on is exactly what memorisation
produces. So a fifth of the pool is held back, never trained on, and used to answer the
only question that matters: does this work on a world it has never seen.
"""

from __future__ import annotations

import random
from dataclasses import dataclass


@dataclass(frozen=True)
class SectorPool:
    """Sectors to draw episodes from, split into a training and a held-out half."""

    train: tuple[int, ...]
    evaluate: tuple[int, ...]
    threats: dict[int, float]

    def __len__(self) -> int:
        return len(self.train) + len(self.evaluate)

    def pick(self, rng: random.Random, evaluating: bool = False) -> int:
        """One sector, drawn uniformly from the appropriate half."""
        pool = self.evaluate if evaluating else self.train
        return rng.choice(pool)

    def hardest(self, evaluating: bool = False) -> float:
        pool = self.evaluate if evaluating else self.train
        return max(self.threats[index] for index in pool) if pool else 0.0


#: One sector in five is held back. Enough to measure with, small enough that the training
#: pool stays in the hundreds where generalisation starts to appear.
EVAL_SHARE = 5


def build_pool(
    listing: dict,
    threat_limit: float = 1.0,
    seed: int = 20260824,
    worlds: int | None = None,
) -> SectorPool:
    """Split the planet's generated sectors into a training set and a held-out set.

    The split is by a seeded shuffle rather than by index, because sector indices follow
    the planet's grid: taking every fifth one would hand the evaluation set a band of the
    globe, and a band of the globe is a biome. A shuffle mixes terrain types across both
    halves, which is what makes the held-out score mean "a world it has not seen" rather
    than "a kind of world it has not seen".

    Threat is the game's own difficulty estimate for a sector, and capping it is the only
    curriculum knob that costs nothing: the pool can be widened as the agent copes.
    """
    indices = [int(i) for i in listing.get("sectors", [])]
    threats = {i: float(t) for i, t in zip(indices, listing.get("threats", []))}

    eligible = sorted(i for i in indices if threats.get(i, 1.0) <= threat_limit)
    if not eligible:
        raise ValueError(
            f"no generated sector at threat {threat_limit} or below; "
            f"the planet ranges {min(threats.values(), default=0):.2f} "
            f"to {max(threats.values(), default=0):.2f}"
        )

    shuffled = list(eligible)
    random.Random(seed).shuffle(shuffled)

    held = tuple(sorted(shuffled[::EVAL_SHARE]))
    rest = [i for i in shuffled if i not in set(held)]

    # The cap applies to the training half only. Narrowing what an agent trains on is a
    # curriculum decision; narrowing what it is judged on would just make the measurement
    # easier, which is the one thing it must not be.
    trained = tuple(sorted(rest if worlds is None else rest[:worlds]))

    # A pool with nothing to train on is a configuration mistake, not a small pool.
    if not trained:
        raise ValueError(f"the pool of {len(eligible)} sectors leaves nothing to train on")

    return SectorPool(train=trained, evaluate=held, threats=threats)
